import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.models import (
    Investigation,
    Report,
    Event,
    UnknownGap,
    Hypothesis,
    ExpectedEvidence,
    CounterfactualFactor,
    NextBestEvidence
)
from app.schemas.schemas import ReportResponse, ReportCreate
from app.config import settings

router = APIRouter(tags=["Reports"])

@router.get("/api/reports", response_model=List[ReportResponse])
def list_reports(db: Session = Depends(get_db)):
    return db.query(Report).order_by(Report.created_at.desc()).all()

@router.get("/api/reports/{id}", response_model=ReportResponse)
def get_report(id: str, db: Session = Depends(get_db)):
    rep = db.query(Report).filter(Report.id == id).first()
    if not rep:
        raise HTTPException(status_code=404, detail="Report not found")
    return rep

@router.get("/api/investigations/{investigation_id}/report", response_model=ReportResponse)
def get_investigation_report(investigation_id: str, db: Session = Depends(get_db)):
    rep = db.query(Report).filter(Report.investigation_id == investigation_id).first()
    if not rep:
        raise HTTPException(status_code=404, detail="No report found for this investigation")
    return rep

@router.post("/api/investigations/{investigation_id}/report", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
def generate_report(
    investigation_id: str,
    db: Session = Depends(get_db)
):
    inv = db.query(Investigation).filter(Investigation.id == investigation_id).first()
    if not inv:
        raise HTTPException(status_code=404, detail="Investigation not found")

    events = db.query(Event).filter(Event.investigation_id == investigation_id).order_by(Event.timestamp.asc()).all()
    gaps = db.query(UnknownGap).filter(UnknownGap.investigation_id == investigation_id).all()
    hypotheses = db.query(Hypothesis).filter(Hypothesis.investigation_id == investigation_id).all()
    next_best = db.query(NextBestEvidence).filter(NextBestEvidence.investigation_id == investigation_id).all()

    # Build rich report structure conforming to prompt specifications:
    # Investigation Overview, Evidence Sources, Observed Events, Unified Timeline,
    # Unknown Gaps, Hypotheses, Supporting/Contradicting/Missing Evidence,
    # Expected vs Actual, What Would Change My Mind?, Next-Best Evidence,
    # Limitations, AI Assistance Disclosure
    report_json = {
        "investigation_overview": {
            "title": inv.title,
            "domain": inv.domain,
            "description": inv.description,
            "status": inv.status,
            "is_synthetic_demo": inv.is_synthetic_demo
        },
        "observed_events": [
            {
                "timestamp": e.timestamp,
                "type": e.event_type,
                "description": e.description,
                "location": e.location,
                "status": e.status,
                "confidence": e.confidence
            }
            for e in events
        ],
        "unknown_gaps": [
            {
                "window": f"{g.start_time} - {g.end_time}",
                "duration": g.duration,
                "preceding": g.preceding_event,
                "following": g.following_event,
                "significance": g.significance,
                "missing_sources": g.sources_missing
            }
            for g in gaps
        ],
        "hypotheses": [
            {
                "title": h.title,
                "description": h.description,
                "status": h.status,
                "heuristic_score": h.heuristic_score,
                "assumptions": h.assumptions,
                "supporting_evidence": h.supporting_evidence,
                "contradicting_evidence": h.contradicting_evidence,
                "missing_evidence": h.missing_evidence
            }
            for h in hypotheses
        ],
        "next_best_evidence": [
            {
                "source": nb.source,
                "location": nb.location,
                "time_window": nb.time_window,
                "priority": nb.priority,
                "reason": nb.reason,
                "heuristic_info_value": nb.heuristic_info_value
            }
            for nb in next_best
        ],
        "limitations": [
            "Continuous visual coverage is absent between 10:02:18 and 10:02:27.",
            "Heuristic scores reflect relative model confidence and are not calibrated statistical probabilities.",
            "Local camera SD cards and municipal traffic archives remain uncollected."
        ],
        "ai_disclosure": "Generated by TRACE-X Heuristic Reasoning Engine with Gemini AI integration.",
        "legal_disclaimer": settings.LEGAL_DISCLAIMER
    }

    report = db.query(Report).filter(Report.investigation_id == investigation_id).first()
    summary_text = (
        f"Forensic synthesis for '{inv.title}' spanning {len(events)} events and {len(gaps)} unknown gaps. "
        f"{len(hypotheses)} competing hypotheses analyzed. Priority action: inspect Camera C3 local SD storage."
    )

    if report:
        report.title = f"Investigation Final Synthesis: {inv.title}"
        report.summary = summary_text
        report.content_json = report_json
        report.legal_disclaimer = settings.LEGAL_DISCLAIMER
    else:
        report = Report(
            id=str(uuid.uuid4()),
            investigation_id=investigation_id,
            title=f"Investigation Final Synthesis: {inv.title}",
            summary=summary_text,
            content_json=report_json,
            legal_disclaimer=settings.LEGAL_DISCLAIMER
        )
        db.add(report)

    db.commit()
    db.refresh(report)
    return report
